# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /Classification_app

# Copy the current directory contents into the container at /app
COPY . /Classification_app

# Install any needed packages specified in requirements.txt
RUN apt-get update \
    && apt-get install -y libhdf5-dev \
    && pip install --no-cache-dir -r requirements.txt

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Run app.py when the container launches
CMD ["streamlit", "run", "Classification_app.py"]
