FROM python:3.8-slim-buster

WORKDIR /app

COPY Classification_app.py /app
COPY functions.py /app

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Run app.py when the container launches
CMD ["streamlit", "run", "--server.port", "8080", "Classification_app.py"]
